### ISSUE TITLE
The Computer Container doesn't show up in the mobile version

### ISSUE THREAD

**Issue by choubari** [AbdallahAbis/AbdallahAbis-v2#8]
Hey There, 

I saw your portfolio, well designed and have a really good look and animations. However in the Mobile Version, The Computer Illustration / Container doesn't appear in the mobile version.

![Screenshot_20210104-231900_Chrome](https://user-images.githubusercontent.com/56233818/103586406-4c544300-4ee5-11eb-80cc-50d66f3e68a6.jpg)

![demo](https://user-images.githubusercontent.com/56233818/103586418-56764180-4ee5-11eb-9e6d-e4ee3eba5ed2.png)

**Comment by AbdallahAbis** [comment]
Thank you for your feedback, I meant to hide it on mobile because it won't look good on mobile. I used it on desktop because I needed something to fill up the right area with.

Thanks
